os: linux
language: cpp
compiler: clang
notifications:
    slack: gqcg:13JQ7AAK5DMZPeAInhCMX6YJ
    email: false

install:
  - true

script:
  - mkdir build && cd build
  - cmake ..
  - make && make test